import React from 'react';

function Reporting() {
  return (
    <div className="reporting">
      <div className="page-header">
        <h1>Reporting & Analytics</h1>
        <div className="page-actions">
          <button className="btn btn-primary">Generate Report</button>
          <button className="btn btn-secondary">Export Data</button>
        </div>
      </div>

      <div className="grid grid-2">
        <div className="card">
          <h2>Colorado State Reporting</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div>
              <h4>Immunization Registry (CIIS)</h4>
              <p>Last sync: 2025-01-11 08:00 AM</p>
              <span className="badge badge-success">Up to date</span>
            </div>
            <div>
              <h4>PDMP Reporting</h4>
              <p>Last submission: 2025-01-10 11:30 PM</p>
              <span className="badge badge-success">Compliant</span>
            </div>
            <div>
              <h4>Medicaid MMIS</h4>
              <p>Claims submitted: 45 this week</p>
              <span className="badge badge-info">Active</span>
            </div>
          </div>
        </div>

        <div className="card">
          <h2>Quality Metrics</h2>
          <div style={{ display: 'grid', gap: '1rem' }}>
            <div>
              <strong>Patient Safety:</strong>
              <div className="progress-bar">
                <div style={{ width: '95%', backgroundColor: 'var(--success-color)', height: '8px', borderRadius: '4px' }}></div>
              </div>
              <small>95.5%</small>
            </div>
            <div>
              <strong>Preventive Care:</strong>
              <div className="progress-bar">
                <div style={{ width: '87%', backgroundColor: 'var(--success-color)', height: '8px', borderRadius: '4px' }}></div>
              </div>
              <small>87.3%</small>
            </div>
            <div>
              <strong>Chronic Care Management:</strong>
              <div className="progress-bar">
                <div style={{ width: '78%', backgroundColor: 'var(--warning-color)', height: '8px', borderRadius: '4px' }}></div>
              </div>
              <small>78.4%</small>
            </div>
          </div>
        </div>
      </div>

      <div className="card">
        <h2>Available Reports</h2>
        <div className="grid grid-3">
          <button className="btn btn-secondary">Financial Report</button>
          <button className="btn btn-secondary">Demographics Report</button>
          <button className="btn btn-secondary">Provider Productivity</button>
          <button className="btn btn-secondary">Quality Measures</button>
          <button className="btn btn-secondary">Billing Summary</button>
          <button className="btn btn-secondary">Custom Report</button>
        </div>
      </div>

      <div className="card">
        <h2>Recent Activity</h2>
        <table className="table">
          <thead>
            <tr>
              <th>Report Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Monthly Financial Summary</td>
              <td>Admin User</td>
              <td>2025-01-10</td>
              <td>
                <button className="btn btn-sm btn-primary">Download</button>
              </td>
            </tr>
            <tr>
              <td>Quality Metrics Q4 2024</td>
              <td>Admin User</td>
              <td>2025-01-05</td>
              <td>
                <button className="btn btn-sm btn-primary">Download</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default Reporting;
